<?php

/**
 * @file
 * Contains functions related to the module functionality and Drupal hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function imagefield_tokens_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the image_field_tokens module.
    case 'help.page.image_field_tokens':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The ImageField Tokens module extends
      the default functionality of Image Widget and Formatter and adding
      the ability to specify default values and use content entity tokens
      in the Alt and Title text.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_filefield_sources_widgets().
 *
 * This returns a list of widgets that are compatible with FileField Sources.
 */
function imagefield_tokens_filefield_sources_widgets() {
  return array('file_generic', 'image_image', 'imagefield_tokens');
}
