<?php

function bsbuidling_preprocess_page(&$variables) {

  _buidl_guide_get_support_link($variables);
}  



/**
 * Implements hook_theme_suggestions_container_alter().
 */
function bsbuidling_theme_suggestions_container_alter(array &$suggestions, array $variables) {
  $pieces = [
    $variables['element']['#type'],
    //$variables['element']['#name'],
    //$variables['element']['#display_id'],
  ];
  $suggestions[] = 'container__' . implode('_', $pieces);
  $suggestions[] = 'container__' . $variables['element']['#type'];
  //$suggestions[] = 'container__' . $variables['element']['#name'];
}
/**
 * Implements hook_theme_suggestions_page_alter().
 */
function bsbuidling_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__node__' . $node->bundle();
  }
}

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function bsbuidling_theme_suggestions_field_alter(&$suggestions, $variables) {
  $suggestions[] = 'field__' . 
    $variables['element']['#field_name'] . '__' . 
    $variables['element']['#view_mode'];
}


function bsbuidling_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  $files = array(
    'core/modules/system/css/components/align.module.css',
    'core/modules/system/css/components/fieldgroup.module.css',
    'core/modules/system/css/components/container-inline.module.css',
    'core/modules/system/css/components/clearfix.module.css',
    'core/modules/system/css/components/details.module.css',
    'core/modules/system/css/components/hidden.module.css',
    'core/modules/system/css/components/item-list.module.css',
    'core/modules/system/css/components/js.module.css',
    'core/modules/system/css/components/nowrap.module.css',
    'core/modules/system/css/components/position-container.module.css',
    'core/modules/system/css/components/progress.module.css',
    'core/modules/system/css/components/reset-appearance.module.css',
    'core/modules/system/css/components/resize.module.css',
    'core/modules/system/css/components/sticky-header.module.css',
    'core/modules/system/css/components/system-status-counter.css',
    'core/modules/system/css/components/system-status-report-counters.css',
    'core/modules/system/css/components/system-status-report-general-info.css', 
    'core/modules/system/css/components/tablesort.module.css',
    'core/modules/system/css/components/tree-child.module.css',
    //'core/modules/user/css/user.module.css',
    'core/modules/views/css/views.module.css',
    'core/assets/vendor/jquery.ui/themes/base/core.css',
    'core/assets/vendor/jquery.ui/themes/base/menu.css',
    'core/assets/vendor/jquery.ui/themes/base/autocomplete.css',
    //'modules/extlink/extlink.css',
    'core/assets/vendor/jquery.ui/themes/base/theme.css',
    'modules/search_api_autocomplete/css/search_api_autocomplete.css',
    //'themes/bootstrap/css/3.4.0/overrides-flatly.min.css',
    //'themes/bsbuidling/css/libs.css',
    //'https://cdn.jsdelivr.net/npm/bootswatch@3.4.0/flatly/bootstrap.css',
    'modules/contrib/social_auth/css/auth-icons.css',
  );
  foreach($files as $file) {
    unset($css[$file]);
  }
}

function bsbuidling_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  $files_d = array(
    'core/misc/autocomplete.js',
    'themes/bootstrap/js/misc/progress.js',
    'core/assets/vendor/jquery.ui/ui/data-min.js',
    'core/assets/vendor/jquery.ui/ui/disable-selection-min.js',
    'core/assets/vendor/jquery.ui/ui/form-min.js',
    'core/assets/vendor/jquery.ui/ui/labels-min.js',
    'core/assets/vendor/jquery.ui/ui/jquery-1-7-min.js',
    'core/assets/vendor/jquery.ui/ui/scroll-parent-min.js',
    'core/assets/vendor/jquery.ui/ui/tabbable-min.js',
    'core/assets/vendor/jquery.ui/ui/unique-id-min.js',
    'core/assets/vendor/jquery.ui/ui/version-min.js',
    'core/assets/vendor/jquery.ui/ui/focusable-min.js',
    'core/assets/vendor/jquery.ui/ui/ie-min.js',
    'core/assets/vendor/jquery.ui/ui/keycode-min.js',
    'core/assets/vendor/jquery.ui/ui/plugin-min.js',
    'core/assets/vendor/jquery.ui/ui/safe-active-element-min.js',
    'core/assets/vendor/jquery.ui/ui/safe-blur-min.js',
    'core/assets/vendor/jquery.ui/ui/widget-min.js',    
    'core/misc/progress.js',
    'core/modules/responsive_image/js/responsive_image.ajax.js',

  );
  $files = array(
    'core/assets/vendor/jquery/jquery.min.js',
    'core/assets/vendor/domready/ready.min.js',
    'core/assets/vendor/underscore/underscore-min.js',
    'core/assets/vendor/jquery/jquery-extend-3.4.0.js',
    'core/misc/drupalSettingsLoader.js',
    'core/misc/drupal.js',
    'core/misc/drupal.init.js',
    'modules/google_analytics/js/google_analytics.js',
    'themes/bootstrap/js/drupal.bootstrap.js',
    'themes/bootstrap/js/attributes.js',
    'themes/bootstrap/js/theme.js',
    

  );
  foreach($files as $file) {
    unset($javascript[$file]);
  }  
}



